name: Package Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop master
on:
  push:
    branches: [ master ]
    paths:
      - '**'
  pull_request:
    branches: [ master ]
    paths:
      - '**'

env:
  flutter_version: '3.10.5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  format:
    name: Flutter Format & Tests

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup Flutter SDK from Cache or cache new
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: stable
          cache: true
          cache-key: '${{ runner.OS }}-flutter-sdk-cache-${{ env.flutter_version }}'
          cache-path: '${{runner.tool_cache}}/flutter'
          architecture: x64

      # Log Flutter version
      - name: Log Flutter version
        run: flutter --version

      # Download all Flutter packages
      - name: Download dependencies
        run: flutter pub get

      # Run Dart Format to ensure formatting is valid
      - name: Run Dart Format
      - run: dart format lib test --set-exit-if-changed
        if: matrix.channel == 'master'

      # Run Flutter tests to ensure basic working
      - name: Run Flutter Tests
        run: flutter test --coverage

      # Upload code coverage details to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          name: Versatile Dialogs (CI Check)
          file: coverage/lcov.info
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
